name: CMake

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare (ubuntu)
      run: |
           sudo apt-get update
           sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

    - name: Install
      run: |
           mkdir install
           cmake --install ${{github.workspace}}/build --strip

    - name: Pack
      run: |
           cd ${{github.workspace}}/build
           cpack -C ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: liblava-2024
        path: ${{github.workspace}}/build/packages/

  release:

    needs: build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: liblava-2024

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          commit: "flow"
          name: "liblava 2024"
          body: "- Updated binaries compared to the [official release](https://github.com/liblava/liblava/releases)"
          artifacts: "liblava-2024.zip"